# Generated by Django 4.1.3 on 2022-11-28 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='date',
        ),
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 18, 18, 16, 266793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ad',
            name='post',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 18, 18, 16, 266793, tzinfo=datetime.timezone.utc)),
        ),
    ]
