# Generated by Django 4.1.3 on 2022-11-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ad_date_ad_created_ad_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='post',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
