# Generated by Django 4.1.3 on 2022-11-28 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_created_alter_ad_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='post',
        ),
        migrations.AddField(
            model_name='ad',
            name='postdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ad',
            name='posttime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
